-- Create table
create table OMPROD.OM_BATCH_OCC
(
  ID_BILLING_ACCOUNT VARCHAR2(20),
  ID_CONTRACT        VARCHAR2(20),
  ID_PLAN            VARCHAR2(20),
  ID_PACKAGE_SERVICE VARCHAR2(20),
  ID_SERVICE         VARCHAR2(20),
  TYPE_MONEY         VARCHAR2(20),
  COST               NUMBER,
  DESCRIPTION        VARCHAR2(30),
  GSM                VARCHAR2(20),
  LEVEL_ADD_OCCN     NUMBER,
  DATE_OPERACTION    DATE,
  FUPACKIDPUB        VARCHAR2(20),
  EFDATE             DATE,
  NUMPERIODS         NUMBER,
  FUPSEQ             VARCHAR2(20),
  ELEMVERSION        VARCHAR2(20),
  FREEUNITSAMOUNT    VARCHAR2(20)
);