-- Create table
create table OMPROD.OM_BATCH_CANCELLATION
(
  ID_BILLING_ACCOUNT    VARCHAR2(20),
  ID_CONTRACT           VARCHAR2(20),
  ID_PLAN               VARCHAR2(20),
  GSM                   VARCHAR2(20),
  SIMCARD               VARCHAR2(20),
  IMSI                  VARCHAR2(20),
  LEVEL_CANCELLATION    NUMBER not null,
  DESCRIPTION_OPERATION VARCHAR2(50)
);