CREATE OR REPLACE TYPE OMPROD.om_obj_get_ord AS OBJECT
(
  id_order                VARCHAR2(10),
  id_ord_type             VARCHAR2(10),
  id_ord_account          VARCHAR2(10),
  cus_type_id             VARCHAR2(10),
  cus_num_id              VARCHAR2(50),
  id_billing              VARCHAR2(10),
  id_billing_account      VARCHAR2(10),
  co_code                 VARCHAR2(10),
  msisdn                  VARCHAR2(144),
  order_status            NUMBER,
  order_status_msg        VARCHAR2(255),
  id_external_app_err     VARCHAR2(10) ,
  id_external_app_err_msg VARCHAR2(255),
  customer_name           VARCHAR2(255),
  prgcode                 VARCHAR2(10) ,
  open_amount             NUMBER,
  installment_amount      NUMBER,
  invoice_number          VARCHAR2(144),
  inv_billingdate         DATE,
  inv_duedate             DATE,
  ins_duedate             DATE,
  email                   VARCHAR2(255),
  reconnection_charge     NUMBER,
  administrative_charge   NUMBER,
  threshold_id            VARCHAR2(10),
  th_consumption          NUMBER,
  th_unit                 VARCHAR2(144),
  tm_code                 VARCHAR2(200),
  list_ord_item           OMPROD.om_list_get_ord_item,
  list_process            OMPROD.om_list_get_process,
  list_ord_il             OMPROD.om_list_get_ord_il
);